services:
  ms-crud:
    build: ./ms-crud
    ports:
      - "3000:3000" 
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/testdb
    volumes:
      - ./secrets:/secrets
    depends_on:
      - mongo
    networks:
      - mynetwork

  ms-profile:
    build: ./ms-profile
    ports:
      - "3001:3001" 
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/testdb
    volumes:
      - ./secrets:/secrets
    depends_on:
      - mongo
    networks:
      - mynetwork

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"   # Expose HTTP on port 8080
      - "4443:443"  # Expose HTTPS on port 4443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./secrets:/etc/nginx/certs
    depends_on:
      - ms-crud
      - ms-profile
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mongo-data:
    driver: local
